name: Lona

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check if Lona is enabled on this repo
        id: lona
        uses: Lona/lona-github-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          WORKFLOW_SUCCEEDED: ${{ job.status == 'success' }}

      - name: Get the latest version of the repository
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "8.x"

      - name: Restore the dependencies cache
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node

      - name: Install the Lona Compiler
        run: npm install lonac @lona/workspace-to-sketch-library

      - name: Create Output Folder
        run: mkdir -p ${{ steps.lona.outputs.output_folder }}

      - name: Extract the list of design tokens
        run: ./node_modules/.bin/lonac flatten --workspace . > ${{ steps.lona.outputs.output_folder }}/flat-json.json

      - name: Generate the Sketch library
        run: 'node -e "require(''@lona/workspace-to-sketch-library'')(process.cwd(), ''${{ steps.lona.outputs.output_folder }}/sketch-library.sketch'', { logFunction: console.log.bind(console) }).catch(err => { console.log(err); process.exit(1); })"'

      - name: Bump the workspace version
        id: tag_version
        uses: mathieudutour/github-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

      - name: Create a GitHub release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          draft: "false"
          prerelease: "false"

      - name: Publish the Sketch Library to the release
        id: upload_sketch_library
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.lona.outputs.output_folder }}/sketch-library.sketch
          asset_name: library.sketch
          asset_content_type: application/zip

      - name: Publish the design tokens to the release
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.lona.outputs.output_folder }}/flat-json.json
          asset_name: tokens.json
          asset_content_type: application/json
      - name: Generate the documentation website
        run: echo "use compiler to generate html"
        env:
          SKETCH_LIBRARY_URL: ${{ steps.upload_sketch_library.outputs.browser_download_url }}
